/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.*;
import BLL.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hong Xuan
 */
public class hoadon extends javax.swing.JFrame {

    DefaultTableModel cthd = new DefaultTableModel();
    double tongtienthuoc = 0;
    double tongtiendv = 0;

    /**
     * Creates new form hoadon
     */
    public hoadon() {
        initComponents();
        cthd.addColumn("Mã Thuốc");// làm sao để biết được tên thuốc
        cthd.addColumn("Tên Thuốc");
        cthd.addColumn("Giá");
        cthd.addColumn("Số Lượng");
        cthd.addColumn("Thành Tiền");
        tablechitiethoadon.setModel(cthd);
        this.sethoadon();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void sethoadon() {
        hoadonngay.setDate(java.util.Date.from(Instant.now()));
        DateFormat sdf = new SimpleDateFormat("HH:mm");
        SimpleDateFormat sdf1=new SimpleDateFormat("yyyy-MM-dd");
        String ngay=sdf1.format(hoadonngay.getDate());
        String tmp = sdf.format(java.util.Calendar.getInstance().getTime());
        tfhoadongio.setText(tmp);
        hoadoncbbtendv.removeAllItems();
        hoadoncbbtt.removeAllItems();
        dichvukhambenh_BLL dvkbBLL = new dichvukhambenh_BLL();
        ArrayList<String> arrtendv = new ArrayList<String>();
        arrtendv = dvkbBLL.gettendv();
        for (int i = 0; i < arrtendv.size(); i++) {
            String a = arrtendv.get(i);
            hoadoncbbtendv.addItem(a);
        }
        tfgiadichvu.setEditable(false);
        String tendv = (String) hoadoncbbtendv.getSelectedItem();
        double giadv = dvkbBLL.getgia(tendv);
        tfgiadichvu.setText(String.valueOf(giadv));
        tfgiadichvu.setEditable(false);
        thuoc_BLL thuoc = new thuoc_BLL();
        ArrayList<String> arrtenthuoc = new ArrayList<String>();
        arrtenthuoc = thuoc.getallten();
        for (int i = 0; i < arrtenthuoc.size(); i++) {
            String a = arrtenthuoc.get(i);
            hoadoncbbtt.addItem(a);
        }
        tfgiathuoc.setEditable(false);
        String tenthuoc = (String) hoadoncbbtt.getSelectedItem();
        double giathuoc = thuoc.getgia(tenthuoc);
        tfgiathuoc.setText(String.valueOf(giathuoc));
        tfhoadongio.setEditable(false);
        hoadonngay.setDateFormatString(ngay);
        tfhdmanv.setEditable(false);
    }
    public void setManv(String manv)
    {
        tfhdmanv.setText(manv);
    }
    public void showtablechitiethoadon(String mahoadon) {

        cthd.setColumnCount(0);
        cthd.setRowCount(0);
        cthd.addColumn("Mã Thuốc");// làm sao để biết được tên thuốc
        cthd.addColumn("Tên Thuốc");
        cthd.addColumn("Giá");
        cthd.addColumn("Số Lượng");
        cthd.addColumn("Thành Tiền");
        ArrayList<chitiethoadon_DTO> arr = new ArrayList<chitiethoadon_DTO>();
        //hoadon_BLL hdBLL=new hoadon_BLL();
        chitiethoadon_BLL cthd_BLL = new chitiethoadon_BLL();
        arr = cthd_BLL.theoma(mahoadon);
        for (int i = 0; i < arr.size(); i++) {
            chitiethoadon_DTO cthd_DTO = arr.get(i);
            String mahd = cthd_DTO.getMahd();
            String mathuoc = cthd_DTO.getMathuoc();
            String tenthuoc = cthd_BLL.gettenthuoc(mathuoc);
            double gia = cthd_BLL.getgia(mathuoc);
            int sl = cthd_DTO.getSl();

            double thanhtien = gia * sl;
            tongtienthuoc += thanhtien;
            Object[] obj = {mathuoc, tenthuoc, gia, sl, thanhtien};
            cthd.addRow(obj);
        }
        tablechitiethoadon.setModel(cthd);
    }

    public void showhoadon(hoadon_DTO hd) {

        tfmahd.setText(hd.getMahd());
        tfmahd.setEditable(false);
        tfhdmanv.setText(hd.getManv());
        tfhdmanv.setEditable(false);
        tfhdmabn.setText(hd.getMabn());
        tfhdmabn.setEditable(false);
        String dateString = hd.getNgay();
        dichvukhambenh_BLL dvkbBLL = new dichvukhambenh_BLL();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date date = df.parse(dateString);
            hoadonngay.setDate(date);
            hoadonngay.setEnabled(false);
        } catch (ParseException ex) {
            System.out.println("hé lô Mai Hồng Xuân!!" + ex);
        }
        tftongdv.setText(dvkbBLL.tongdv(hd.getMabn()));
        tfhoadongio.setText(hd.getGio());
        tfhoadongio.setEditable(false);
        btnthem.setVisible(false);
        this.showtablechitiethoadon(hd.getMahd());
        tfgiadichvu.setEnabled(false);
        hoadoncbbtendv.setEnabled(false);
        lbdvkb.setEnabled(false);
        lbgiadv.setEnabled(false);
        lbslthuoc.setEnabled(false);
        lbtenthuoc.setEnabled(false);
        tfslthuoc.setEnabled(false);
        hoadoncbbtt.setEnabled(false);
        tftongdv.setEditable(false);
        double tongtiendv = dvkbBLL.tonggiadv(hd.getMabn());
        lbtongtiendv.setText("Tiền dịch vụ : " + tongtiendv);
        lbtongtienthuoc.setText("Tiền thuốc : " + tongtienthuoc);
        double tongcong = tongtiendv + tongtienthuoc;
        lbthanhtien.setText("Thành tiền : " + tongcong);
        btnthemdv.setVisible(false);
        btnxoadichvu.setVisible(false);
        btnxoahang.setVisible(false);
        btnthemthuoc.setVisible(false);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfmahd = new javax.swing.JTextField();
        tfhdmanv = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfhdmabn = new javax.swing.JTextField();
        lbdvkb = new javax.swing.JLabel();
        lbgiadv = new javax.swing.JLabel();
        tfgiadichvu = new javax.swing.JTextField();
        hoadoncbbtt = new javax.swing.JComboBox<>();
        lbtenthuoc = new javax.swing.JLabel();
        lbslthuoc = new javax.swing.JLabel();
        tfslthuoc = new javax.swing.JSpinner();
        llbgiathuoc = new javax.swing.JLabel();
        tfgiathuoc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablechitiethoadon = new javax.swing.JTable(){
            @Override
            public boolean isCellEditable(int row,int columns)
            {
                return false;
            }
        };
        btnthem = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();
        hoadonngay = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        lbthanhtien = new javax.swing.JLabel();
        lbtongtiendv = new javax.swing.JLabel();
        lbtongtienthuoc = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfhoadongio = new javax.swing.JTextField();
        hoadoncbbtendv = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        tftongdv = new javax.swing.JTextField();
        btnthemdv = new javax.swing.JButton();
        btnthemthuoc = new javax.swing.JButton();
        btnxoahang = new javax.swing.JButton();
        btnxoadichvu = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jLabel1.setText("HÓA ĐƠN");

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel2.setText("Date : ");

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel3.setText("Mã nhân viên");

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel4.setText("Mã Hóa Đơn");

        tfmahd.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        tfmahd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmahdActionPerformed(evt);
            }
        });

        tfhdmanv.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel6.setText("Mã bệnh nhân");

        tfhdmabn.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        tfhdmabn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhdmabnActionPerformed(evt);
            }
        });

        lbdvkb.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lbdvkb.setText("Dịch vụ");

        lbgiadv.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lbgiadv.setText("Giá ");

        tfgiadichvu.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        tfgiadichvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfgiadichvuActionPerformed(evt);
            }
        });

        hoadoncbbtt.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        hoadoncbbtt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Digoxin_tim", "Nitroglycerin_tim", "Isosorbid_tim", "Quinidin_tim", "Amiodaron_tim", "Nifedipin_tim", "Captopril_tim", "Adrenalin_tim", "Acemuc_phổi", "Halixol_phổi", "Acetylcystein STADA_phổi", "salmeterol_phổi", "formoterol_phổi", "Macrolid_phổi", "Doxycyclin_phổi", "Leucovorin_phổi", "5 – flourouracil_phổi", "Irinotecan_phổi", "Oxaliplatin_phổi", "Bevacizumab_phổi", "Cetuximab_phổi", "clopheniramin", "cetirizin", "5 – diphenylhydramin", "loratadin", "fexodenadin", "Loratadine", "Cetirizine" }));
        hoadoncbbtt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                hoadoncbbttItemStateChanged(evt);
            }
        });

        lbtenthuoc.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lbtenthuoc.setText("Tên thuốc");

        lbslthuoc.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lbslthuoc.setText("SL");
        lbslthuoc.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                lbslthuocComponentAdded(evt);
            }
        });

        tfslthuoc.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        llbgiathuoc.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        llbgiathuoc.setText("Giá");

        tablechitiethoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablechitiethoadon);

        btnthem.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Add.png"))); // NOI18N
        btnthem.setText("Thêm Hóa Đơn");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnthoat.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnthoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Exit.png"))); // NOI18N
        btnthoat.setText("Thoát");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        lbthanhtien.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        lbthanhtien.setText("Tổng cộng : ");

        lbtongtiendv.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lbtongtiendv.setText("Tiền dịch vụ : ");

        lbtongtienthuoc.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lbtongtienthuoc.setText("Tiền thuốc : ");

        jLabel15.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        jLabel15.setText("Giờ");

        hoadoncbbtendv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        hoadoncbbtendv.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                hoadoncbbtendvItemStateChanged(evt);
            }
        });
        hoadoncbbtendv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hoadoncbbtendvMouseClicked(evt);
            }
        });
        hoadoncbbtendv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoadoncbbtendvActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel16.setText("Tổng dịch vụ Khám: ");

        tftongdv.setEditable(false);

        btnthemdv.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        btnthemdv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Create.png"))); // NOI18N
        btnthemdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemdvActionPerformed(evt);
            }
        });

        btnthemthuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Create.png"))); // NOI18N
        btnthemthuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemthuocActionPerformed(evt);
            }
        });

        btnxoahang.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnxoahang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cut.png"))); // NOI18N
        btnxoahang.setText("Xóa 1 Hàng");
        btnxoahang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoahangActionPerformed(evt);
            }
        });

        btnxoadichvu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cut.png"))); // NOI18N
        btnxoadichvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoadichvuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbdvkb)
                            .addComponent(lbtenthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(hoadoncbbtt, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                    .addComponent(hoadoncbbtendv, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfhoadongio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(tfhdmanv, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbgiadv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfgiadichvu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnthemdv)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnxoadichvu, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(llbgiathuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfgiathuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbslthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfslthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnthemthuoc))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfhdmabn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hoadonngay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(tfmahd, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(215, 215, 215))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(btnxoahang, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tftongdv, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbtongtienthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbtongtiendv, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(lbthanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(325, 325, 325))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfmahd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel15)
                            .addComponent(tfhoadongio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hoadonngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfhdmanv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfhdmabn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(hoadoncbbtendv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnxoadichvu)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbgiadv)
                                    .addComponent(tfgiadichvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbdvkb))
                                .addComponent(btnthemdv)))
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbtenthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hoadoncbbtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(llbgiathuoc)
                        .addComponent(tfgiathuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbslthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfslthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnthemthuoc, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tftongdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtongtienthuoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtongtiendv, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbthanhtien))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnxoahang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnthoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnthem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfhdmabnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhdmabnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhdmabnActionPerformed

    private void lbslthuocComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_lbslthuocComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lbslthuocComponentAdded

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát?", "Thông báo!!", JOptionPane.CANCEL_OPTION);
        if (a == 0) {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnthoatActionPerformed

    private void hoadoncbbtendvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoadoncbbtendvMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_hoadoncbbtendvMouseClicked

    private void hoadoncbbtendvItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_hoadoncbbtendvItemStateChanged
        // TODO add your handling code here:
        dichvukhambenh_BLL dvkbBLL = new dichvukhambenh_BLL();
        String tendv = (String) hoadoncbbtendv.getSelectedItem();
        double gia = dvkbBLL.getgia(tendv);
        tfgiadichvu.setText(String.valueOf(gia));
    }//GEN-LAST:event_hoadoncbbtendvItemStateChanged

    private void hoadoncbbttItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_hoadoncbbttItemStateChanged
        // TODO add your handling code here:
        thuoc_BLL thuoc = new thuoc_BLL();
        tfgiathuoc.setEditable(false);
        String tenthuoc = (String) hoadoncbbtt.getSelectedItem();
        double giathuoc = thuoc.getgia(tenthuoc);
        tfgiathuoc.setText(String.valueOf(giathuoc));
    }//GEN-LAST:event_hoadoncbbttItemStateChanged

    private void hoadoncbbtendvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoadoncbbtendvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoadoncbbtendvActionPerformed
    public boolean hasnv(String manv)
    {
        nhanvien_BLL nvBLL=new nhanvien_BLL();
        if(nvBLL.hasnv(manv))
        {
            return true;
        }
        else
        {
            return false;
        }
    }
    public boolean hasbn(String mabn)
    {
        benhnhan_BLL bnBLL=new benhnhan_BLL();
        if(bnBLL.hasbn(mabn))
        {
            return true;
        }
        else
        {
            return false;
        }
    }
    public boolean hashd(String mahd)
    {
        hoadon_BLL hd=new hoadon_BLL();
        if(hd.hashd(mahd)) return true;
        return false;
    }
    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        if (tfmahd.getText().trim().equals("") || tfhdmabn.getText().trim().equals("")
                || tfhdmanv.getText().trim().equals("") || tfhoadongio.getText().equals("")
                || lbthanhtien.getText().equals("Tổng cộng : ")) {
            JOptionPane.showConfirmDialog(this, "Vui long nhập đầy đủ thông tin!!", "thông báo", JOptionPane.CLOSED_OPTION);
            return;
        }
        //tạo dữ liệu
        hoadon_DTO hd = new hoadon_DTO();
        hoadon_BLL hdBLL = new hoadon_BLL();
        thuoc_BLL thuocBLL = new thuoc_BLL();
        thuoc_DTO thuocDTO = new thuoc_DTO();
        chitiethoadon_BLL cthd_BLL = new chitiethoadon_BLL();
        chitiethoadon_DTO cthd_DTO = new chitiethoadon_DTO();
        ArrayList<String> arr = new ArrayList<String>();
        dichvukhambenh_BLL dvkb = new dichvukhambenh_BLL();
        dvbn_DTO dvbnDTO = new dvbn_DTO();
        dvbn_BLL dvbnBLL = new dvbn_BLL();
        String mahd = tfmahd.getText();
        String mabn = tfhdmabn.getText();
        String manv = tfhdmanv.getText();
        String gio = tfhoadongio.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(java.util.Date.from(Instant.now()));
        String tongdv = tftongdv.getText().trim();
        hd.setMahd(mahd);
        hd.setManv(manv);
        hd.setMabn(mabn);
        hd.setGio(gio);
        hd.setNgay(date);
        if(this.hashd(mahd)==true)
        {
            JOptionPane.showConfirmDialog(this, "Mã Hóa đơn đã tồn tại trong hệ thống!", "Thông báo", JOptionPane.CLOSED_OPTION);
            return;
        }
        if(this.hasnv(manv)==false)
        {
            JOptionPane.showConfirmDialog(this, "Nhân Viên không tồn tại trong hệ thống!!!!!!!", "Thông báo", JOptionPane.CLOSED_OPTION);
            return;
        }
         if(this.hasbn(mabn)==false)
         {
             JOptionPane.showConfirmDialog(this, "Bệnh nhân không tồn tại trong hệ thống!!", "Thông báo", JOptionPane.CLOSED_OPTION);
         }
        int a = JOptionPane.showConfirmDialog(this, "bạn có muốn thêm hóa đơn không ???", "Thông Báo", JOptionPane.CANCEL_OPTION);
        
        if (a == 0) {
            for (int i = 0; i < cthd.getRowCount(); i++) {
             cthd_DTO.setMahd(mahd);
             cthd_DTO.setMathuoc((String)tablechitiethoadon.getValueAt(i,0));
             if(cthd_BLL.hascthd(cthd_DTO.getMahd(),cthd_DTO.getMathuoc()))
             {
                 JOptionPane.showConfirmDialog(this, "Chi tiết hóa đơn đã tồn tại, hàng : "+i , "Thông báo", JOptionPane.CLOSED_OPTION);
                 return;
             }
        }
             arr = dvkb.gettendv();
                for (int i = 0; i < arr.size(); i++) {
                    String tendv = arr.get(i);
                    if (tongdv.contains(tendv.trim()))///nếu nó có thì thêm nó vào dvbn
                    {
                        System.out.println(tendv+"          "+tongdv);
                        dvbnDTO.setMabn(mabn);
                        dvbnDTO.setMadv(dvkb.getma(tendv));
                        dvbnDTO.setMahd(mahd);
                        System.out.println(dvbnDTO.getMadv());
                        if (dvbnBLL.hasdvbn(dvbnDTO.getMabn(), dvbnDTO.getMadv(),dvbnDTO.getMahd()) == true) {
                            JOptionPane.showConfirmDialog(this, "dịch vụ của bệnh nhân này đã được thêm vào hệ thống!", "Thông báo", JOptionPane.CLOSED_OPTION);
                            return;
                        }
                    }
                }
            if (hdBLL.them(hd)) {//nếu thêm thành công thì thì cthd va dvkb
                for (int i = 0; i < cthd.getRowCount(); i++) {
                    
                    cthd_DTO.setMahd(mahd);
                    cthd_DTO.setMathuoc((String) cthd.getValueAt(i, 0));
                    cthd_DTO.setSl((int) cthd.getValueAt(i, 3));
                    cthd_DTO.setTt((double) cthd.getValueAt(i, 4));
                    if (cthd_BLL.them(cthd_DTO) == false) {
                        JOptionPane.showConfirmDialog(this, "Lỗi chi tiết của hóa đơn", "Thông báo", JOptionPane.CLOSED_OPTION);
                        return;
                    } else {
                       
                        thuocDTO.setMathuoc((String) cthd.getValueAt(i, 0));
                        thuocDTO.setSl((int) cthd.getValueAt(i, 3));
                        String mathuoc = thuocDTO.getMathuoc();//không cần kiểm tra thuốc chõ này  đặt ở chỗ input rồi
                        int sl = thuocBLL.getsl(mathuoc) - thuocDTO.getSl();
                        if (thuocBLL.capnhatsl(mathuoc, sl) == false) {
                            JOptionPane.showConfirmDialog(this, "Lỗi Cập nhật kho thuốc!!", "thông báo", JOptionPane.CLOSED_OPTION);
                            return;
                        }
                    }
                }
                
                
                arr = dvkb.gettendv();
                for (int i = 0; i < arr.size(); i++) {
                    String tendv = arr.get(i);
                    if (tongdv.contains(tendv.trim()))///nếu nó có thì thêm nó vào dvbn
                    {
                        
                        dvbnDTO.setMabn(mabn);
                        dvbnDTO.setMadv(dvkb.getma(tendv));
                        dvbnDTO.setMahd(mahd);
                        if (dvbnBLL.them(dvbnDTO) == false) {
                            JOptionPane.showConfirmDialog(this, "Lỗi lưu dữ liệu dịch vụ khám bệnh của bệnh nhân", "Thông báo", JOptionPane.CLOSED_OPTION);
                            return;
                        }
                    }
                }
                JOptionPane.showConfirmDialog(this, "Thêm thành công", "Thông Báo", JOptionPane.CLOSED_OPTION);
            } else {
                JOptionPane.showConfirmDialog(this, "Thêm không thành công", "Thông báo", JOptionPane.CLOSED_OPTION);
            }

        }

    }//GEN-LAST:event_btnthemActionPerformed

    private void btnthemdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemdvActionPerformed
        // TODO add your handling code here:
        String a = String.valueOf(hoadoncbbtendv.getSelectedItem());
        String b = tftongdv.getText();

        if (b.contains(a)) {
            JOptionPane.showConfirmDialog(this, "Dịch vụ này đã được chọn!", "Thông báo ", JOptionPane.CLOSED_OPTION);

        } else {
            b += a + " ,";
            tftongdv.setText(b);
            double gia = Double.parseDouble(tfgiadichvu.getText());
            tongtiendv += gia;
            lbtongtiendv.setText("Tiền dịch vụ : " + tongtiendv);
        }
        lbthanhtien.setText("Tổng Cộng : " + (tongtienthuoc + tongtiendv));
    }//GEN-LAST:event_btnthemdvActionPerformed

    private void btnxoadichvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoadichvuActionPerformed
        // TODO add your handling code here:
        String a = String.valueOf(hoadoncbbtendv.getSelectedItem());
        String b = tftongdv.getText();

        if (b.contains(a)) {
            String tmp = b.replaceAll(a + " ,", "");
            tftongdv.setText(tmp);
            double gia = Double.parseDouble(tfgiadichvu.getText());
            tongtiendv -= gia;
            lbtongtiendv.setText("Tiền dịch vụ : " + tongtiendv);
        } else {
            JOptionPane.showConfirmDialog(this, "Dịch vụ này đã chưa đc được chọn!", "Thông báo ", JOptionPane.CLOSED_OPTION);
        }
        lbthanhtien.setText("Tổng Cộng : " + (tongtienthuoc + tongtiendv));
    }//GEN-LAST:event_btnxoadichvuActionPerformed

    private void btnthemthuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemthuocActionPerformed
        // TODO add your handling code here:

        thuoc_DTO thuoc = new thuoc_DTO();
        thuoc_BLL thuoc_BLL = new thuoc_BLL();
        String tenthuoc = String.valueOf(hoadoncbbtt.getSelectedItem());
        thuoc.setTenthuoc(tenthuoc);
        String mathuoc = thuoc_BLL.getmathuoc(tenthuoc);
        for (int i = 0; i < cthd.getRowCount(); i++) {
            String tmp = (String) cthd.getValueAt(i, 0);

            if (mathuoc.equals(tmp.trim())) {
                JOptionPane.showConfirmDialog(this, "Mã thuốc đã được thêm vào bảng!!!", "Thông báo", JOptionPane.CLOSED_OPTION);
                return;
            }
        }
        thuoc.setMathuoc(mathuoc);
        double giathuoc = Double.parseDouble(tfgiathuoc.getText());
        thuoc.setGia(giathuoc);
        int sl = (int) tfslthuoc.getValue();
        if (thuoc_BLL.kiemtrathuoc(mathuoc, sl) == false) {
            JOptionPane.showConfirmDialog(this, "Kho thuốc không đủ số lượng yêu cầu !!", "Thông báo", JOptionPane.CLOSED_OPTION);
            return;
        }
        thuoc.setSl(sl);

        double thanhtien = giathuoc * sl;
        Object[] obj = {mathuoc, tenthuoc, giathuoc, sl, thanhtien};
        cthd.addRow(obj);
        tablechitiethoadon.setModel(cthd);
        for (int i = 0; i < cthd.getRowCount(); i++) {
            tongtienthuoc += (double) cthd.getValueAt(i, 4);

        }
        lbtongtienthuoc.setText("Tiền thuốc : " + tongtienthuoc);

        lbthanhtien.setText("Tổng Cộng : " + (tongtienthuoc + tongtiendv));

    }//GEN-LAST:event_btnthemthuocActionPerformed

    private void tfmahdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmahdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfmahdActionPerformed

    private void btnxoahangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoahangActionPerformed
        // TODO add your handling code here:
        try
        {
            tongtienthuoc = 0;
        int i = tablechitiethoadon.getSelectedRow();
        cthd.removeRow(i);
        tablechitiethoadon.setModel(cthd);
        for (int j = 0; j < cthd.getRowCount(); j++) {
            tongtienthuoc += (double) cthd.getValueAt(j, 4);

        }
        lbtongtienthuoc.setText("Tiền thuốc : " + tongtienthuoc);
        lbthanhtien.setText("Tổng Cộng : " + (tongtienthuoc + tongtiendv));
        }
        catch(ArrayIndexOutOfBoundsException e)
        {
            JOptionPane.showConfirmDialog(this, "Bạn chưa chọn hàng cần xóa.Vui lòng Chọn!!!", "Thông báo", JOptionPane.CLOSED_OPTION);
        }
        
    }//GEN-LAST:event_btnxoahangActionPerformed

    private void tfgiadichvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfgiadichvuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfgiadichvuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hoadon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnthemdv;
    private javax.swing.JButton btnthemthuoc;
    private javax.swing.JButton btnthoat;
    private javax.swing.JButton btnxoadichvu;
    private javax.swing.JButton btnxoahang;
    private javax.swing.JComboBox<String> hoadoncbbtendv;
    private javax.swing.JComboBox<String> hoadoncbbtt;
    private com.toedter.calendar.JDateChooser hoadonngay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbdvkb;
    private javax.swing.JLabel lbgiadv;
    private javax.swing.JLabel lbslthuoc;
    private javax.swing.JLabel lbtenthuoc;
    private javax.swing.JLabel lbthanhtien;
    private javax.swing.JLabel lbtongtiendv;
    private javax.swing.JLabel lbtongtienthuoc;
    private javax.swing.JLabel llbgiathuoc;
    private javax.swing.JTable tablechitiethoadon;
    private javax.swing.JTextField tfgiadichvu;
    private javax.swing.JTextField tfgiathuoc;
    private javax.swing.JTextField tfhdmabn;
    private javax.swing.JTextField tfhdmanv;
    private javax.swing.JTextField tfhoadongio;
    private javax.swing.JTextField tfmahd;
    private javax.swing.JSpinner tfslthuoc;
    private javax.swing.JTextField tftongdv;
    // End of variables declaration//GEN-END:variables
}
